// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace garden_backend.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20260414213620_AddUserRelation")]
    partial class AddUserRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("Models.CareResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("CareResources");

                    b.HasDiscriminator().HasValue("CareResource");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Models.Harvest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessingMethod")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Harvests");
                });

            modelBuilder.Entity("Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlantedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Plants");

                    b.HasDiscriminator().HasValue("Plant");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.Fertilizer", b =>
                {
                    b.HasBaseType("Models.CareResource");

                    b.Property<bool>("IsOrganic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nutrients")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Fertilizer");
                });

            modelBuilder.Entity("Models.PestControl", b =>
                {
                    b.HasBaseType("Models.CareResource");

                    b.Property<string>("TargetPest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WaitingDays")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("PestControl");
                });

            modelBuilder.Entity("Models.BerryBush", b =>
                {
                    b.HasBaseType("Models.Plant");

                    b.Property<bool>("TrellisNeeds")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("BerryBush");
                });

            modelBuilder.Entity("Models.FruitTree", b =>
                {
                    b.HasBaseType("Models.Plant");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("FruitTree");
                });

            modelBuilder.Entity("Models.Harvest", b =>
                {
                    b.HasOne("Models.Plant", "Plant")
                        .WithMany("Harvests")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Models.Plant", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithMany("Plants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Plant", b =>
                {
                    b.Navigation("Harvests");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
